# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [11]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np

<module 'numpy' from '/Users/dehilinesma/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
rg= np.random.default_rng(1)
a= rg.random((2,3,5))
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [79]:
aa= np.random.random((2,3,5))
aa

array([[[0.33493664, 0.95423277, 0.52752361, 0.80590133, 0.02484009],
        [0.42091609, 0.02323701, 0.42311671, 0.87374578, 0.26477972],
        [0.89207945, 0.38890979, 0.16362406, 0.71415347, 0.60986158]],

       [[0.03597032, 0.34618073, 0.67653921, 0.43529009, 0.48360225],
        [0.6693521 , 0.0987206 , 0.00966776, 0.79678469, 0.0686538 ],
        [0.7276856 , 0.13405061, 0.7889287 , 0.36699934, 0.06151474]]])

In [80]:
a=np.empty((2,3,5))
a

array([[[0.33493664, 0.95423277, 0.52752361, 0.80590133, 0.02484009],
        [0.42091609, 0.02323701, 0.42311671, 0.87374578, 0.26477972],
        [0.89207945, 0.38890979, 0.16362406, 0.71415347, 0.60986158]],

       [[0.03597032, 0.34618073, 0.67653921, 0.43529009, 0.48360225],
        [0.6693521 , 0.0987206 , 0.00966776, 0.79678469, 0.0686538 ],
        [0.7276856 , 0.13405061, 0.7889287 , 0.36699934, 0.06151474]]])

#### 4. Print *a*.


NameError: name 'a' is not defined

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [14]:
b=np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [15]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
a.size


30

In [22]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
np.add(a,b) 
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [34]:
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [35]:
d

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [36]:
e=a*c


In [37]:
e

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
d_max=np.max(d)
d_max

1.9807371998012386

In [41]:
d_min=np.min(d)
d_min

1.0275591132430684

In [50]:
d_mean=np.mean(d)
d_mean

1.5135194619749464

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [73]:
f=np.empty((2,3,5))
f

array([[[75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.]],

       [[75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.],
        [75., 75., 75., 75., 75.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
for i1 in range(0,2):
    for i2 in range(0,3):
        for i3 in range(0,5):
            if d_min< d[i1,i2,i3] < d_mean:
                f[i1,i2,i3] = 25
            elif d_mean< d[i1,i2,i3] < d_max:
                f[i1,i2,i3] = 75
            elif d[i1,i2,i3] == d_mean:
                f[i1,i2,i3] = 50
            elif d[i1,i2,i3] == d_min:
                f[i1,i2,i3] = 0
            else:
                f[i1,i2,i3] = 100
print(f)

[[[ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.  75.   0.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [77]:
print(d)
print(f)

[[[1.51182162 1.9504637  1.14415961 1.94864945 1.31183145]
  [1.42332645 1.82770259 1.40919914 1.54959369 1.02755911]
  [1.75351311 1.53814331 1.32973172 1.7884287  1.30319483]]

 [[1.45349789 1.1340417  1.40311299 1.20345524 1.26231334]
  [1.75036467 1.28040876 1.48519097 1.9807372  1.96165719]
  [1.72478994 1.54122686 1.2768912  1.16065201 1.96992541]]]
[[[ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.  75.   0.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.